### ISSUE TITLE
Editing a web hook form on version 3.30.0 does not pull in existing values

### ISSUE THREAD

**Issue by robotdan** [CleanSpeak/cleanspeak-issues#21]
### Description 
Once a web hook is created, if you edit it in the admin UI, the current values are not populated in the forum. 

### Expected behavior
To be able to correctly edit a web hook without copying in existing values.

**Comment by voidmain** [comment]
Can we close this one out?

**Comment by robotdan** [comment]
Not sure, I can check. Looks like 3.30.1 is not yet released, but maybe it went into 3.30.0? 
https://cleanspeak.com/docs/3.x/tech/release-notes/

**Comment by robotdan** [comment]
Looks like it was fixed in 3.31.0 but the release notes were not updated. I'll update the release notes, you may have to add some additional details to the release notes, or let me know what went into that release.
