### ISSUE TITLE
Escalation comment not validated for length

### ISSUE THREAD

**Issue by robotdan** [CleanSpeak/cleanspeak-issues#32]
### Description 
When a comment is added to an escalation that is longer than `255`, the escalation will fail. 

We need to validate this length, and ask the moderator to shorten the comment.  

### Steps to reproduce
1. Enter the mod queue
2. Escalate an item
3. Leave a comment longer than `255`

### Expected behavior
A validation error. 

### Exception

```
### SQL: UPDATE queued_content_users SET comment = ?, previous_status = ?, status = ?, update_instant = ?, applications_id = ?, last_update_user_id = ? WHERE id = ?
### Cause: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
...com.inversoft.cleanspeak.api.service.moderation.DefaultContentUserModerationService.escalate(DefaultContentUserModerationService.java:716)
```
### Related
- https://github.com/CleanSpeak/cleanspeak-issues/issues/33

**Comment by brettwp** [comment]
Fixes for this are in `cleanspeak-management-interface` [PR #3](https://github.com/CleanSpeak/cleanspeak-management-interface/pull/3).
