### ISSUE TITLE
Unable to change user score from `/admin/moderation/user`

### ISSUE THREAD

**Issue by brettwp** [CleanSpeak/cleanspeak-issues#43]
### Description
When viewing a user on `/admin/moderation/user` (as opposed to a popup) when you click `submit` to update a user's score you are told "This user is not currently checked out to you" and are unable to change the score.  If you are viewing the user in a popup (e.g. from the dashboard) you are able to update the user score.

### Steps to reproduce
1. Go to `Search -> Users -> Manage` (this will forward you to `/admin/moderation/user` for the user)
2. Click to edit the user's score
3. Click submit

### Expected behavior
Submit should succeed and close the "Edit User Score" dialog.

### Additional context
This appears to be a problem with the `UserRelease.js` listening for clicks and releasing the user when the "Edit User Score" dialog opens on `/admin/moderation/user` pages.  This does not happen for `/ajax/moderation/user` popups.

**Comment by robotdan** [comment]
Released in 3.31.4. I also copied the patch into `master`. @brettwp can you confirm the fix works at `master` and then close out the issue?
