### ISSUE TITLE
Add a bit of Javascript to change default DB ports in CleanSpeak Setup Wizard

### ISSUE THREAD

**Issue by jobannon** [CleanSpeak/cleanspeak-issues#56]
### Problem
When initially setting up CleanSpeak, the ports are prefilled for mySQL (Port `3306`), however, it would be nice to have a little bit of Javascript that can move the defaults to something for PG when this database is selected (Port `5432`, by default)

### Solution
We could use JS to make this user experience a bit more seamless

### Alternatives/workarounds
Manually Enter in the port numbers

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by wied03** [comment]
Fixed in 4.0.
