### ISSUE TITLE
PDF report when exported, does not correctly export as PDF file format (file assoc. issue)

### ISSUE THREAD

**Issue by jobannon** [CleanSpeak/cleanspeak-issues#63]
### Description 
When exporting a PDF report (`weekly report` for instance), the file is downloaded, but it is not associated by name with. a .pdf file extension type.

### Expected behavior
Download a weekly report and have <file_name>.pdf not <file_name> alone.

Currently, this is only problematic on the weekly emailed report, but other reports may exhibit the same behavior.

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]

### Additional context
Internal ticket #2994

### Internal Pull Request 

- https://github.com/CleanSpeak/cleanspeak-api/pull/6

**Comment by robotdan** [comment]
@jobannon do you have a PR for `-webservice` and `management-interface` as well? Thinking there should be at least one or PR?

**Comment by jobannon** [comment]
@robotdan I tested this locally and only this one change is needed at the API level.  After a review, I could not find where webservice and MI would need changes.  I think this is the only code that calls `generate` for our PdfService.  

Can think on it a bit, as well...
