### ISSUE TITLE
Add optional support for accessing the status endpoint w/ an API key

### ISSUE THREAD

**Issue by robotdan** [CleanSpeak/cleanspeak-issues#70]
### Problem
Ideally we'd add support for using an API key on the status endpoint. This would be a breaking change unless we allow it to be optionally configured. 

### Solution
- Require an API key
- W/out an API key you get a status code a simple "ok" 

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by wied03** [comment]
Covered in 4.0.
